apiVersion: 1

deleteRules:
  - orgId: 1
    uid: availability-watch-rate-limited

contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack-contact-point
        type: slack
        settings:
          url: ${GRAFANA_SLACK_WEBHOOK_URL}

policies:
  - orgId: 1
    receiver: slack
    group_by:
      - grafana_folder
      - alertname
    routes: []

muteTimes: []
templates: []
