apiVersion: 1

datasources:
  - name: Tempo
    uid: roadtrip-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: roadtrip-prometheus
      tracesToLogsV2:
        datasourceUid: roadtrip-loki
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{container=~"roadtrip-backend.*"} | json | mdc_trace_id="$${__trace.traceId}"'
