package ca.floo.roadtrip.apigen

import ca.floo.roadtrip.model.api.ApiContract
import ca.floo.roadtrip.model.api.ApiEndpoint
import ca.floo.roadtrip.model.api.guardBodyClasses
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.serializer
import kotlin.reflect.KClass
import kotlin.reflect.full.createType

private const val GENERATED_HEADER =
    """// Generated by `./gradlew :backend:generateApiTypes` (`make api-types`) from the
// Kotlin @Serializable DTOs named in
// backend/src/main/kotlin/ca/floo/roadtrip/model/api/ApiContract.kt.
//
// Do not edit by hand. `make test` and CI run `:backend:checkApiTypes`, which
// fails when this file and the DTOs disagree.
//
// Optionality follows the one encoder (route/common/RouteResponses.kt:
// encodeDefaults = true, explicitNulls = false). In a response body a field is
// optional exactly when it is nullable, and a non-null field with a default is
// always sent; in a request body a field is optional when it is nullable or has
// a default. A nullable arm is never generated, because a Kotlin null is never
// encoded; a `JsonNull` value inside a `Json*` field still is.
//
// Every Kotlin integer is a TypeScript `number`: the ids are database bigints
// that stay well below 2^53.
//
// Each API_ENDPOINTS row states the status of every body it can serve. 401 and
// 403 are absent wherever the route's declared access level supplies them; see
// /api/docs/openapi.json for the merged picture.
"""

@Suppress("TopLevelPropertyNaming")
private val IDENTIFIER = Regex("^[A-Za-z_$][A-Za-z0-9_$]*$")

/**
 * Everything one walk of the contract produced. Rows stay in declaration order.
 *
 * [guardSchemas] is the claimed name of every class an access guard answers
 * with — no row names them, and the OpenAPI builder publishes them on each
 * gated operation, so the walk claims them here rather than letting the
 * reference site re-derive a name the collision map never approved.
 */
internal data class ContractWalk(
    val interfaces: List<TsInterface>,
    val enums: List<TsEnum>,
    val rows: List<TsEndpoint>,
    val guardSchemas: Map<KClass<*>, String>,
)

/**
 * One walk of the descriptor graph from every row of [endpoints], under both
 * optionality rules, sharing one name-collision map.
 *
 * The single source both renderers read: [generateApiTypes] writes the
 * TypeScript from it and `OpenApiContractDocument` writes `components/schemas`
 * and the per-operation bodies from the same result, so a schema can never name
 * a type the TypeScript does not declare. Rows are **not** sorted here: the
 * document builder zips them against `ApiContract.endpoints` positionally.
 */
internal fun walkContract(endpoints: List<ApiEndpoint> = ApiContract.endpoints): ContractWalk {
    val declaredBy = HashMap<String, String>()
    val responses = DescriptorWalk(Optionality.RESPONSE, declaredBy)
    val requests = DescriptorWalk(Optionality.REQUEST, declaredBy)
    // The row takes the names the walks claimed, so no consumer can name a type
    // the collision map has not approved.
    val rows =
        endpoints.map { endpoint ->
            TsEndpoint(
                method = endpoint.method.wireValue,
                path = endpoint.path,
                request = endpoint.request?.let { requests.declaredName(it) },
                success =
                    TsBody(
                        endpoint.success.status,
                        endpoint.success.body?.let { responses.declaredName(it) },
                    ),
                errors =
                    endpoint.errors
                        .map { body -> TsBody(body.status, body.body?.let { responses.declaredName(it) }) }
                        .distinct()
                        .sortedWith(compareBy({ it.status }, { it.type.orEmpty() })),
            )
        }
    // Claimed before the declarations are read off the walk: a guard class no row
    // mentions is a declaration in its own right, and would otherwise be a `$ref`
    // to a schema `components` never got.
    val guardSchemas = guardBodyClasses.associateWith { responses.declaredName(it) }
    return ContractWalk(
        interfaces = merge(responses.interfaces, requests.interfaces),
        enums = (responses.enums + requests.enums).values.toList(),
        rows = rows,
        guardSchemas = guardSchemas,
    )
}

/**
 * The whole generated file, for [endpoints]. Deterministic: declarations sorted
 * by name, fields in declaration order, endpoints sorted by path then method.
 */
internal fun generateApiTypes(endpoints: List<ApiEndpoint> = ApiContract.endpoints): String {
    val walk = walkContract(endpoints)
    return render(
        interfaces = walk.interfaces,
        enums = walk.enums,
        endpoints = walk.rows.sortedWith(compareBy({ it.path }, { it.method })),
    )
}

/** The claimed declaration name for a contract row's class, walking it on first mention. */
private fun DescriptorWalk.declaredName(kClass: KClass<*>): String =
    when (val type = typeOf(kClass.descriptor())) {
        is WireType.Ref -> type.name
        is WireType.EnumRef -> type.name
        else ->
            throw ApiTypeGenerationException(
                "${kClass.qualifiedName} is named by a contract row, but its descriptor is a $type " +
                    "rather than a declared class or enum. A request, response or error body must be a " +
                    "@Serializable class or enum.",
            )
    }

private fun KClass<*>.descriptor(): SerialDescriptor {
    // A contract row names a KClass, which carries no type arguments, so
    // createType() below would hand reflection an under-applied type and fail
    // with a message that names neither the DTO nor the row.
    if (typeParameters.isNotEmpty()) {
        throw ApiTypeGenerationException(
            "$qualifiedName is generic. A contract row names a KClass, which carries no type " +
                "arguments, so the generator cannot resolve its serializer. Declare a concrete DTO " +
                "(e.g. WatchPage) rather than Page<Watch>.",
        )
    }
    return serializer(createType()).descriptor
}

/**
 * One interface per class. A class both sides reach must describe the same
 * shape under both optionality rules; when it stops doing so the build says
 * which fields disagree, and whoever needs the second variant designs it then.
 */
private fun merge(
    responses: Map<String, TsInterface>,
    requests: Map<String, TsInterface>,
): List<TsInterface> {
    responses.keys.intersect(requests.keys).forEach { serialName ->
        val fromResponse = responses.getValue(serialName)
        val fromRequest = requests.getValue(serialName)
        if (fromResponse == fromRequest) return@forEach
        val differing =
            fromResponse.fields
                .zip(fromRequest.fields)
                .filter { (response, request) -> response != request }
                .joinToString { (response, _) -> response.name }
        throw ApiTypeGenerationException(
            "$serialName is both a request body and a response body, and the two optionality rules " +
                "disagree on: $differing. Split it into two DTOs, or give the request field the same " +
                "nullability the response has.",
        )
    }
    return (responses + requests).values.sortedBy { it.name }
}

private fun render(
    interfaces: List<TsInterface>,
    enums: List<TsEnum>,
    endpoints: List<TsEndpoint>,
): String =
    buildString {
        append(GENERATED_HEADER)
        (enums.map { it.name to renderEnum(it) } + interfaces.map { it.name to renderInterface(it) })
            .sortedBy { it.first }
            .forEach { append("\n").append(it.second) }
        append("\n").append(renderEndpoints(endpoints))
    }

private fun renderEnum(tsEnum: TsEnum): String = "export type ${tsEnum.name} = ${tsEnum.values.joinToString(" | ") { "'$it'" }};\n"

private fun renderInterface(tsInterface: TsInterface): String =
    buildString {
        append("export interface ${tsInterface.name} {\n")
        tsInterface.fields.forEach { field ->
            append("  ${key(field.name)}${if (field.optional) "?" else ""}: ${tsTypeOf(field.type)};\n")
        }
        append("}\n")
    }

private fun renderEndpoints(endpoints: List<TsEndpoint>): String =
    buildString {
        append("export const API_ENDPOINTS = [\n")
        endpoints.forEach { endpoint ->
            append("  { method: '${endpoint.method}', path: '${endpoint.path}'")
            append(", request: ${quoted(endpoint.request)}")
            append(", success: ${renderBody(endpoint.success)}")
            append(", errors: [${endpoint.errors.joinToString(transform = ::renderBody)}] },\n")
        }
        append("] as const;\n")
    }

private fun renderBody(body: TsBody): String = "{ status: ${body.status}, type: ${quoted(body.type)} }"

private fun quoted(name: String?): String = name?.let { "'$it'" } ?: "null"

/** A wire key that is not a bare TypeScript identifier has to be quoted. */
private fun key(name: String): String = if (IDENTIFIER.matches(name)) name else "'$name'"
