package ca.floo.roadtrip.apigen

import ca.floo.roadtrip.model.api.ApiContract
import ca.floo.roadtrip.model.api.ApiEndpoint
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.serializer
import kotlin.reflect.KClass
import kotlin.reflect.full.createType

private const val GENERATED_HEADER =
    """// Generated by `./gradlew :backend:generateApiTypes` (`make api-types`) from the
// Kotlin @Serializable DTOs named in
// backend/src/main/kotlin/ca/floo/roadtrip/model/api/ApiContract.kt.
//
// Do not edit by hand. `make test` and CI run `:backend:checkApiTypes`, which
// fails when this file and the DTOs disagree.
//
// Optionality follows the one encoder (route/common/RouteResponses.kt:
// encodeDefaults = true, explicitNulls = false). In a response body a field is
// optional exactly when it is nullable, and a non-null field with a default is
// always sent; in a request body a field is optional when it is nullable or has
// a default. A nullable arm is never generated, because null is never encoded.
//
// Every Kotlin integer is a TypeScript `number`: the ids are database bigints
// that stay well below 2^53.
"""

@Suppress("TopLevelPropertyNaming")
private val IDENTIFIER = Regex("^[A-Za-z_$][A-Za-z0-9_$]*$")

/**
 * The whole generated file, for [endpoints]. Deterministic: declarations sorted
 * by name, fields in declaration order, endpoints sorted by path then method.
 */
internal fun generateApiTypes(endpoints: List<ApiEndpoint> = ApiContract.endpoints): String {
    val declaredBy = HashMap<String, String>()
    val responses = DescriptorWalk(Optionality.RESPONSE, declaredBy)
    val requests = DescriptorWalk(Optionality.REQUEST, declaredBy)
    endpoints.forEach { endpoint ->
        (listOfNotNull(endpoint.response) + endpoint.errors).forEach { responses.typeOf(it.descriptor()) }
        endpoint.request?.let { requests.typeOf(it.descriptor()) }
    }
    return render(
        interfaces = merge(responses.interfaces, requests.interfaces),
        enums = (responses.enums + requests.enums).values.toList(),
        endpoints = endpointRows(endpoints),
    )
}

private fun KClass<*>.descriptor(): SerialDescriptor = serializer(createType()).descriptor

/**
 * One interface per class. A class both sides reach must describe the same
 * shape under both optionality rules; when it stops doing so the build says
 * which fields disagree, and whoever needs the second variant designs it then.
 */
private fun merge(
    responses: Map<String, TsInterface>,
    requests: Map<String, TsInterface>,
): List<TsInterface> {
    responses.keys.intersect(requests.keys).forEach { serialName ->
        val fromResponse = responses.getValue(serialName)
        val fromRequest = requests.getValue(serialName)
        if (fromResponse == fromRequest) return@forEach
        val differing =
            fromResponse.fields
                .zip(fromRequest.fields)
                .filter { (response, request) -> response != request }
                .joinToString { (response, _) -> response.name }
        throw ApiTypeGenerationException(
            "$serialName is both a request body and a response body, and the two optionality rules " +
                "disagree on: $differing. Split it into two DTOs, or give the request field the same " +
                "nullability the response has.",
        )
    }
    return (responses + requests).values.sortedBy { it.name }
}

private fun endpointRows(endpoints: List<ApiEndpoint>): List<TsEndpoint> =
    endpoints
        .map { endpoint ->
            TsEndpoint(
                method = endpoint.method.wireValue,
                path = endpoint.path,
                request = endpoint.request?.let { tsName(it.descriptor().serialName) },
                response = endpoint.response?.let { tsName(it.descriptor().serialName) },
            )
        }.sortedWith(compareBy({ it.path }, { it.method }))

private fun render(
    interfaces: List<TsInterface>,
    enums: List<TsEnum>,
    endpoints: List<TsEndpoint>,
): String =
    buildString {
        append(GENERATED_HEADER)
        (enums.map { it.name to renderEnum(it) } + interfaces.map { it.name to renderInterface(it) })
            .sortedBy { it.first }
            .forEach { append("\n").append(it.second) }
        append("\n").append(renderEndpoints(endpoints))
    }

private fun renderEnum(tsEnum: TsEnum): String = "export type ${tsEnum.name} = ${tsEnum.values.joinToString(" | ") { "'$it'" }};\n"

private fun renderInterface(tsInterface: TsInterface): String =
    buildString {
        append("export interface ${tsInterface.name} {\n")
        tsInterface.fields.forEach { field ->
            append("  ${key(field.name)}${if (field.optional) "?" else ""}: ${field.type};\n")
        }
        append("}\n")
    }

private fun renderEndpoints(endpoints: List<TsEndpoint>): String =
    buildString {
        append("export const API_ENDPOINTS = [\n")
        endpoints.forEach { endpoint ->
            append("  { method: '${endpoint.method}', path: '${endpoint.path}'")
            append(", request: ${quoted(endpoint.request)}")
            append(", response: ${quoted(endpoint.response)} },\n")
        }
        append("] as const;\n")
    }

private fun quoted(name: String?): String = name?.let { "'$it'" } ?: "null"

/** A wire key that is not a bare TypeScript identifier has to be quoted. */
private fun key(name: String): String = if (IDENTIFIER.matches(name)) name else "'$name'"
