roadtrip:
  static-dir: /app/static
  db:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  booking:
    recgov-atc:
      companion-base-url: http://recgov-companion:8770
  grafana:
    root-url: http://127.0.0.1:3000/dash/
  web:
    root-url: http://127.0.0.1:8765
