server:
  port: 8765
  admin-port: 8766

roadtrip:
  static-dir: /app/static
  db:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  grafana:
    root-url: https://roadtrip.floo.ca/dash/
  web:
    root-url: https://roadtrip.floo.ca/
