roadtrip:
  static-dir: /app/static
  auth:
    role-emails:
      admin:
        - williamchen16@gmail.com
  db:
    url: "${POSTGRES_URL:jdbc:postgresql://postgres:5432/roadtrip}"
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  booking:
    recgov-atc:
      companion-base-url: "http://recgov-companion:8770"
  grafana:
    root-url: "https://roadtrip.floo.ca/dash/"
  web:
    root-url: "${ROADTRIP_WEB_ROOT_URL:https://roadtrip.floo.ca/}"
