roadtrip:
  static-dir: .
  db:
    url: jdbc:postgresql://localhost:5432/roadtrip
    user: roadtrip
    password: roadtrip
  booking:
    recgov-atc:
      companion-base-url: http://127.0.0.1:8770
  grafana:
    root-url: http://127.0.0.1:3000/dash/
  web:
    root-url: http://127.0.0.1:8765
