#!/usr/bin/env python3
"""Secrets for the roadtrip stack: encrypted in git, mounted as files at runtime.

Everything lives in this directory:

    registry.yaml       which secrets exist, who gets them, where they're required
    common.enc.env      values shared by every environment
    local.enc.env       overlay for `tilt up` / `make run`
    prod.enc.env        overlay for `make run env=prod`
    .sops.yaml          age recipients
    manage.py           this tool

A vault is a dotenv whose *values* are age-encrypted and whose *keys* are
plaintext, so `git diff` shows which secret changed without showing what it
changed to. All of it is committed: durability is git history, and deploying a
secret is the same `git pull` that deploys code.

Nothing is ever decrypted to a file. `exec` merges common + the environment's
overlay in memory and replaces itself with the target command; Docker Compose
then turns those environment values into /run/secrets/<name> file mounts, so
containers read files and the values never appear in `docker inspect` or the
host process table.

    ./secrets/manage.py exec prod -- docker compose up -d

Environments mirror application-{local,prod}.yaml, so one word selects both the
app profile and its secrets.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SECRETS_DIR = Path(__file__).resolve().parent
ROOT = SECRETS_DIR.parent

REGISTRY_FILE = SECRETS_DIR / "registry.yaml"
SOPS_CONFIG = SECRETS_DIR / ".sops.yaml"
GENERATED_COMPOSE = ROOT / "docker-compose.secrets.yml"

COMMON_ENV = "common"
ENVIRONMENTS = ("local", "prod")

# Consumers that are Compose services and receive a mounted file. `host-tools`
# runs outside containers, so those get environment injection from `exec`
# instead — there is nowhere to mount a file.
SERVICE_CONSUMERS = ("postgres", "backend", "grafana", "cloudflared")

GENERATED_HEADER = "# GENERATED by secrets/manage.py — do not edit."

# One key path on every host, macOS and Linux alike. sops would otherwise
# resolve this with Go's os.UserConfigDir(), which differs per platform and
# makes runbooks stop being copy-pasteable. run_sops passes it explicitly.
AGE_KEY_FILE = Path(
    os.environ.get(
        "SOPS_AGE_KEY_FILE", Path.home() / ".config" / "sops" / "age" / "keys.txt"
    )
)

ADOPTABLE_AGE_KEY_FILES = [
    path
    for path in (
        Path.home() / "Library" / "Application Support" / "sops" / "age" / "keys.txt",
        Path.home() / ".config" / "sops" / "age" / "keys.txt",
    )
    if path != AGE_KEY_FILE
]

SOPS_FORMAT_ARGS = ["--input-type", "dotenv", "--output-type", "dotenv"]

# age-keygen writes the public half as a comment beside the private key.
AGE_PUBLIC_KEY_COMMENT = "# public key:"

# An age public key is bech32: "age1" plus 58 characters of bech32's alphabet,
# which omits 1, b, i and o. Checking the shape before it reaches .sops.yaml
# turns a truncated paste into an error now, rather than a vault that re-wraps
# cleanly and still cannot be opened by the machine it was meant to enroll.
AGE_PUBLIC_KEY_RE = re.compile(r"age1[02-9ac-hj-np-z]{58}")

# Where recipients live in .sops.yaml. Each is a list item under `- age:`,
# preceded by a comment naming its holder.
AGE_BLOCK_RE = re.compile(r"^(\s*)-\s+age:\s*$")
RECIPIENT_RE = re.compile(r"^(\s*)-\s+(age1[02-9ac-hj-np-z]+)\s*$")
# Indent of a recipient relative to the `- age:` line: past the "- ", then one
# nesting level in. Only used when the block is empty and has no line to copy.
AGE_BLOCK_ITEM_INDENT = " " * 4

PRIVATE_KEY_WARNING = (
    "The private half is not in the repo and cannot be recovered. Back it up."
)

# sops exits 200 from `edit` when the editor closed without changing anything.
# An outcome, not a failure.
SOPS_EXIT_NO_CHANGE = 200
SOPS_METADATA_PREFIX = "sops_"

AGE_KEY_FILE_MODE = 0o600


class SecretsError(RuntimeError):
    """A failure whose message is already written for a human."""


# --------------------------------------------------------------------------
# registry
#
# Parsed with the standard library only: PyYAML is not installed anywhere in
# this repo (the one script that imports it cannot even load), and a secrets
# tool that fails to start because of a missing dependency is worse than a
# small parser. The file is still valid YAML — the Kotlin side reads it with
# Ktor's real parser — so this handles exactly the shape `add` writes:
# top-level NAME:, two-space-indented `key: value`, and `[a, b]` inline lists.
# Anything outside that shape raises rather than being silently misread.
# --------------------------------------------------------------------------

ENTRY_RE = re.compile(r"^([A-Z][A-Z0-9_]*):\s*$")
FIELD_RE = re.compile(r"^  ([a-z_]+):\s*(.*)$")


class Secret:
    def __init__(self, name: str, description: str, consumers: list[str],
                 required_in: list[str]):
        self.name = name
        self.description = description
        self.consumers = consumers
        self.required_in = required_in

    @property
    def file_name(self) -> str:
        """Compose secret name and the basename under /run/secrets."""
        return self.name.lower()

    def services(self) -> list[str]:
        """Compose services that should receive this as a mounted file."""
        return [c for c in self.consumers if c in SERVICE_CONSUMERS]


def parse_registry(text: str) -> dict[str, Secret]:
    secrets: dict[str, Secret] = {}
    name: str | None = None
    fields: dict[str, object] = {}

    def flush() -> None:
        if name is None:
            return
        missing = {"description", "consumers", "required_in"} - fields.keys()
        if missing:
            raise SecretsError(f"{name} in registry.yaml is missing: {', '.join(sorted(missing))}")
        secrets[name] = Secret(
            name=name,
            description=str(fields["description"]),
            consumers=list(fields["consumers"]),  # type: ignore[arg-type]
            required_in=list(fields["required_in"]),  # type: ignore[arg-type]
        )

    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        entry = ENTRY_RE.match(raw)
        if entry:
            flush()
            name, fields = entry.group(1), {}
            continue
        field = FIELD_RE.match(raw)
        if field and name is not None:
            key, value = field.group(1), field.group(2).strip()
            if value.startswith("[") and value.endswith("]"):
                inner = value[1:-1].strip()
                fields[key] = [v.strip() for v in inner.split(",") if v.strip()]
            elif value in {"true", "false"}:
                fields[key] = value == "true"
            else:
                fields[key] = value
            continue
        raise SecretsError(f"registry.yaml: cannot parse line: {raw!r}")
    flush()
    if not secrets:
        raise SecretsError("registry.yaml declares no secrets")
    return secrets


def load_registry() -> dict[str, Secret]:
    if not REGISTRY_FILE.exists():
        raise SecretsError(f"{REGISTRY_FILE.relative_to(ROOT)} is missing")
    return parse_registry(REGISTRY_FILE.read_text())


# --------------------------------------------------------------------------
# dotenv
#
# Deliberately dumb: split on the first `=`, keep the remainder verbatim.
# Cookie headers and connection strings contain `=`, `;` and quotes, and the
# consumer sees the raw value, so any "helpful" unquoting would corrupt it.
# --------------------------------------------------------------------------


def parse_dotenv(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        if key and not key.startswith(SOPS_METADATA_PREFIX):
            values[key] = value
    return values


# --------------------------------------------------------------------------
# sops
# --------------------------------------------------------------------------


def require_tools(*names: str) -> None:
    missing = [n for n in names if shutil.which(n) is None]
    if missing:
        raise SecretsError(
            f"missing required tool(s): {', '.join(missing)}\n"
            f"Install with: brew install {' '.join(missing)}"
        )


def misplaced_age_key() -> Path | None:
    if AGE_KEY_FILE.exists():
        return None
    return next((p for p in ADOPTABLE_AGE_KEY_FILES if p.exists()), None)


def run_sops(args: list[str], *, capture: bool = True, stdin: str | None = None,
             allow: tuple[int, ...] = ()) -> tuple[int, str]:
    require_tools("sops")
    env = {**os.environ, "SOPS_AGE_KEY_FILE": str(AGE_KEY_FILE)}
    proc = subprocess.run(
        ["sops", *args],
        cwd=SECRETS_DIR,
        input=stdin,
        capture_output=capture,
        text=True,
        env=env,
    )
    if proc.returncode != 0 and proc.returncode not in allow:
        detail = (proc.stderr or proc.stdout or "").strip() if capture else ""
        # sops' "did not find keys in locations ..." lists only environment
        # variables, so a key in the wrong directory reads as no key at all.
        stranded = misplaced_age_key()
        hint = (
            f"\n\nhint: an age identity exists at {stranded}, but this repo keeps it at"
            f"\n      {AGE_KEY_FILE}. Adopt it with: ./secrets/manage.py enroll"
            if stranded
            else ""
        )
        raise SecretsError(f"sops failed ({' '.join(args)})\n{detail}{hint}")
    return proc.returncode, (proc.stdout if capture else "")


def vault_path(env_name: str) -> Path:
    return SECRETS_DIR / f"{env_name}.enc.env"


def read_vault(env_name: str) -> dict[str, str]:
    path = vault_path(env_name)
    if not path.exists():
        raise SecretsError(
            f"{path.relative_to(ROOT)} does not exist.\n"
            "First-time setup: ./secrets/manage.py enroll, then ./secrets/manage.py import"
        )
    _, plaintext = run_sops(["--decrypt", *SOPS_FORMAT_ARGS, path.name])
    return parse_dotenv(plaintext)


def write_vault(env_name: str, values: dict[str, str]) -> None:
    """Encrypt values into a vault via stdin, so no plaintext reaches disk."""
    path = vault_path(env_name)
    body = "".join(f"{k}={v}\n" for k, v in sorted(values.items()))
    # An empty vault still has to be a valid encrypted file; give it a comment
    # to carry the sops metadata.
    if not body:
        body = "# (no values for this environment)\n"
    _, ciphertext = run_sops(
        ["--encrypt", *SOPS_FORMAT_ARGS, "--filename-override", path.name, "/dev/stdin"],
        stdin=body,
    )
    path.write_text(ciphertext)


def load_merged(env_name: str) -> dict[str, str]:
    """Every registered secret, with common + the environment's overlay applied.

    Registered-but-unset secrets are exported as empty strings rather than
    omitted. Compose refuses to start when an `environment:`-sourced secret's
    variable is unset, so omitting them would make registering a secret you
    have not filled in yet break the whole stack. Empty is also the state the
    application already understands: ConfigSection maps "" to null and
    SecretsBootstrap counts blank as missing, so an unset optional secret
    disables its feature exactly as before.
    """
    if env_name not in ENVIRONMENTS:
        raise SecretsError(
            f"unknown environment '{env_name}'. Expected one of: {', '.join(ENVIRONMENTS)}"
        )
    merged = {name: "" for name in load_registry()}
    merged.update(read_vault(COMMON_ENV))
    merged.update({k: v for k, v in read_vault(env_name).items() if v})
    return merged


# --------------------------------------------------------------------------
# generation — this is what makes `consumers` enforceable rather than decorative
# --------------------------------------------------------------------------


def render_compose(registry: dict[str, Secret]) -> str:
    """Render docker-compose.secrets.yml from the registry.

    Compose sources each secret from an environment variable, which `exec`
    supplies in memory, and mounts it at /run/secrets/<name>. So the value is
    a file inside the container and never a container environment variable.
    """
    by_service: dict[str, list[Secret]] = {}
    for secret in registry.values():
        for service in secret.services():
            by_service.setdefault(service, []).append(secret)

    lines = [
        GENERATED_HEADER,
        "#",
        "# Source: secrets/registry.yaml (the `consumers` field).",
        "# Regenerate: ./secrets/manage.py generate",
        "#",
        "# Compose is invoked with `-f docker-compose.yml -f docker-compose.secrets.yml`.",
        "# Because this file is what actually runs, a wrong `consumers` entry means the",
        "# container genuinely does not get the secret — the registry cannot drift from",
        "# reality without something breaking loudly.",
        "",
        "services:",
    ]
    for service in sorted(by_service):
        lines.append(f"  {service}:")
        lines.append("    secrets:")
        for secret in sorted(by_service[service], key=lambda s: s.name):
            lines.append(f"      - {secret.file_name}")
    lines.append("")
    lines.append("secrets:")
    for secret in sorted(
        {s.name: s for svc in by_service.values() for s in svc}.values(),
        key=lambda s: s.name,
    ):
        lines.append(f"  {secret.file_name}:")
        lines.append(f"    environment: {secret.name}")
    return "\n".join(lines) + "\n"


def cmd_generate(args: argparse.Namespace) -> int:
    rendered = render_compose(load_registry())
    current = GENERATED_COMPOSE.read_text() if GENERATED_COMPOSE.exists() else ""
    if args.check:
        if current != rendered:
            print(
                f"error: {GENERATED_COMPOSE.name} is stale. "
                "Run: ./secrets/manage.py generate",
                file=sys.stderr,
            )
            return 1
        print(f"{GENERATED_COMPOSE.name} is up to date")
        return 0
    if current == rendered:
        print(f"{GENERATED_COMPOSE.name} already current")
        return 0
    GENERATED_COMPOSE.write_text(rendered)
    print(f"wrote {GENERATED_COMPOSE.name}")
    return 0


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------


def cmd_exec(args: argparse.Namespace) -> int:
    """Replace this process with `command`, secrets in its environment.

    execvpe rather than a subprocess: nothing lingers holding the values, and
    the caller sees the command's own exit code and signals.
    """
    if not args.command:
        raise SecretsError("usage: manage.py exec <env> -- <command>")
    command = args.command[1:] if args.command[0] == "--" else args.command
    # Real environment wins, so `FOO=bar make run` still overrides for one-off
    # debugging.
    env = {**load_merged(args.environment), **os.environ}
    try:
        os.execvpe(command[0], command, env)
    except FileNotFoundError:
        raise SecretsError(f"command not found: {command[0]}") from None
    return 0  # unreachable


def cmd_export(args: argparse.Namespace) -> int:
    """Emit KEY=VALUE lines for a caller that cannot be exec-wrapped.

    Only the Tiltfile needs this: Tilt runs `docker compose` itself, but its
    Starlark can os.putenv() and subprocesses inherit that. Values cross a pipe
    in memory, never disk — the Tiltfile must read them with quiet=True.
    """
    for key, value in sorted(load_merged(args.environment).items()):
        print(f"{key}={value}")
    return 0


def cmd_ls(args: argparse.Namespace) -> int:
    """List secrets and where each has a value. Never prints a value."""
    registry = load_registry()
    present: dict[str, set[str]] = {}
    for env_name in (COMMON_ENV, *ENVIRONMENTS):
        if not vault_path(env_name).exists():
            continue
        for key, value in read_vault(env_name).items():
            if value:
                present.setdefault(key, set()).add(env_name)

    width = max(len(n) for n in registry)
    print(f"{'SECRET'.ljust(width)}  {'SET IN':<18}  CONSUMERS")
    for name, secret in sorted(registry.items()):
        where = ",".join(sorted(present.get(name, ()))) or "-"
        required = " *" if secret.required_in else ""
        print(f"{name.ljust(width)}  {where:<18}  {','.join(secret.consumers)}{required}")
    unknown = set(present) - set(registry)
    for name in sorted(unknown):
        print(f"{name.ljust(width)}  {'':<18}  !! in a vault but not in registry.yaml")
    print()
    print("* required in at least one environment. Values are never printed; use `get`.")
    return 0 if not unknown else 1


def cmd_get(args: argparse.Namespace) -> int:
    values = load_merged(args.environment)
    if args.name not in values:
        raise SecretsError(f"{args.name} has no value in {args.environment}")
    print(values[args.name])
    return 0


def cmd_set(args: argparse.Namespace) -> int:
    registry = load_registry()
    if args.name not in registry:
        raise SecretsError(
            f"{args.name} is not in registry.yaml. Add it first:\n"
            f"    ./secrets/manage.py add {args.name}"
        )
    value = args.value if args.value is not None else read_secret_value(args.name)
    target = args.environment
    values = read_vault(target)
    values[args.name] = value
    write_vault(target, values)
    print(f"set {args.name} in {target}.enc.env — commit it")
    return 0


def cmd_rm(args: argparse.Namespace) -> int:
    """Remove a secret from every vault and from the registry."""
    removed_from = []
    for env_name in (COMMON_ENV, *ENVIRONMENTS):
        if not vault_path(env_name).exists():
            continue
        values = read_vault(env_name)
        if args.name in values:
            del values[args.name]
            write_vault(env_name, values)
            removed_from.append(env_name)

    registry_text = REGISTRY_FILE.read_text()
    if args.name in load_registry():
        REGISTRY_FILE.write_text(drop_registry_entry(registry_text, args.name))
        print(f"removed {args.name} from registry.yaml")
    if removed_from:
        print(f"removed value from: {', '.join(removed_from)}")
    if not removed_from and args.name not in parse_registry(registry_text):
        raise SecretsError(f"{args.name} is not in the registry or any vault")
    cmd_generate(argparse.Namespace(check=False))
    print("Rotate the credential at its provider — git history still has the old value.")
    return 0


def drop_registry_entry(text: str, name: str) -> str:
    """Remove one entry and the comment block immediately above it."""
    lines = text.splitlines(keepends=True)
    out, i = [], 0
    while i < len(lines):
        if ENTRY_RE.match(lines[i]) and ENTRY_RE.match(lines[i]).group(1) == name:
            # Drop the preceding comment/blank block that documents this entry.
            while out and (out[-1].lstrip().startswith("#") or not out[-1].strip()):
                out.pop()
            i += 1
            while i < len(lines) and (lines[i].startswith("  ") or not lines[i].strip()):
                i += 1
            out.append("\n")
            continue
        out.append(lines[i])
        i += 1
    return "".join(out)


def read_secret_value(name: str) -> str:
    """Read a value without echoing it, and without it landing in shell history."""
    import getpass

    value = getpass.getpass(f"value for {name} (input hidden): ")
    if not value:
        raise SecretsError("empty value — aborting")
    return value


def cmd_add(args: argparse.Namespace) -> int:
    """Register a new secret and set its value in one step."""
    registry = load_registry()
    if args.name in registry:
        raise SecretsError(
            f"{args.name} is already registered. Change its value with:\n"
            f"    ./secrets/manage.py set {args.name} {args.environment}"
        )
    if not re.fullmatch(r"[A-Z][A-Z0-9_]*", args.name):
        raise SecretsError(f"'{args.name}' must be UPPER_SNAKE_CASE")
    unknown = set(args.consumers) - set(SERVICE_CONSUMERS) - {"host-tools"}
    if unknown:
        raise SecretsError(
            f"unknown consumer(s): {', '.join(sorted(unknown))}. "
            f"Valid: {', '.join((*SERVICE_CONSUMERS, 'host-tools'))}"
        )

    entry = [
        "",
        f"{args.name}:",
        f"  description: {args.description}",
        f"  consumers: [{', '.join(args.consumers)}]",
        f"  required_in: [{', '.join(args.required_in)}]",
    ]
    REGISTRY_FILE.write_text(REGISTRY_FILE.read_text().rstrip("\n") + "\n" + "\n".join(entry) + "\n")
    print(f"registered {args.name}")

    value = args.value if args.value is not None else read_secret_value(args.name)
    values = read_vault(args.environment)
    values[args.name] = value
    write_vault(args.environment, values)
    print(f"set value in {args.environment}.enc.env")
    cmd_generate(argparse.Namespace(check=False))
    print()
    print(f"Commit secrets/registry.yaml, secrets/{args.environment}.enc.env, "
          f"and {GENERATED_COMPOSE.name}.")
    return 0


def cmd_edit(args: argparse.Namespace) -> int:
    path = vault_path(args.environment)
    if not path.exists():
        raise SecretsError(f"{path.relative_to(ROOT)} does not exist")
    code, _ = run_sops(["edit", path.name], capture=False, allow=(SOPS_EXIT_NO_CHANGE,))
    if code == SOPS_EXIT_NO_CHANGE:
        print("vault unchanged.")
        return 0
    print(f"{path.relative_to(ROOT)} updated — commit it")
    return 0


def cmd_import(args: argparse.Namespace) -> int:
    """One-time migration: seed the vaults from a plaintext dotenv."""
    source = Path(args.source).expanduser()
    if not source.exists():
        raise SecretsError(f"{source} does not exist")
    existing = [e for e in (COMMON_ENV, *ENVIRONMENTS) if vault_path(e).exists()]
    if existing and not args.force:
        raise SecretsError(
            f"vault(s) already exist: {', '.join(existing)}. "
            "Use `set`/`edit`, or pass --force to rebuild."
        )
    stale = active_placeholders(SOPS_CONFIG.read_text())
    if stale:
        raise SecretsError(
            "secrets/.sops.yaml still has placeholder recipients:\n"
            + "\n".join(f"    {line}" for line in stale)
        )

    registry = load_registry()
    incoming = parse_dotenv(source.read_text())
    kept = {k: v for k, v in incoming.items() if v and k in registry}
    skipped_unregistered = sorted(k for k, v in incoming.items() if v and k not in registry)

    write_vault(COMMON_ENV, kept)
    for env_name in ENVIRONMENTS:
        write_vault(env_name, {})
    print(f"imported {len(kept)} registered secrets into {COMMON_ENV}.enc.env")
    if skipped_unregistered:
        print(f"skipped (not in registry.yaml): {', '.join(skipped_unregistered)}")
    print("Move environment-specific values into an overlay with `set NAME prod`.")
    return 0


def active_placeholders(text: str) -> list[str]:
    return [
        line.strip()
        for line in text.splitlines()
        if "PLACEHOLDER" in line and not line.strip().startswith("#")
    ]


def cmd_check(args: argparse.Namespace) -> int:
    """Validate registry, vaults and generated output. No age key needed."""
    errors: list[str] = []
    warnings: list[str] = []
    registry = load_registry()

    for line in active_placeholders(SOPS_CONFIG.read_text()):
        errors.append(f"secrets/.sops.yaml has a placeholder recipient: {line}")

    vault_keys: set[str] = set()
    for env_name in (COMMON_ENV, *ENVIRONMENTS):
        path = vault_path(env_name)
        if not path.exists():
            errors.append(f"secrets/{path.name} is missing")
            continue
        text = read_staged(path) if args.staged else path.read_text()
        if f"{SOPS_METADATA_PREFIX}version" not in text:
            errors.append(f"secrets/{path.name} has no sops metadata — it is not encrypted")
        for key, value in parse_dotenv(text).items():
            vault_keys.add(key)
            # An unset key is legitimate and there is nothing to encrypt in an
            # empty string, so sops leaves it alone. Only a populated plaintext
            # value is a leak.
            if value and not value.startswith("ENC["):
                errors.append(f"{key} is not encrypted in secrets/{path.name}")

    for key in sorted(vault_keys - set(registry)):
        errors.append(f"{key} has a value but is not declared in registry.yaml")

    # Required secrets must actually be present somewhere, or the deploy fails
    # at boot rather than here.
    if not args.staged and vault_path(COMMON_ENV).exists() and shutil.which("sops"):
        try:
            for env_name in ENVIRONMENTS:
                if not vault_path(env_name).exists():
                    continue
                have = {k for k, v in load_merged(env_name).items() if v}
                for name, secret in registry.items():
                    if env_name in secret.required_in and name not in have:
                        errors.append(f"{name} is required_in [{env_name}] but has no value there")
        except SecretsError:
            warnings.append("could not decrypt to verify required values (no age key?)")

    if GENERATED_COMPOSE.exists():
        if GENERATED_COMPOSE.read_text() != render_compose(registry):
            errors.append(
                f"{GENERATED_COMPOSE.name} is stale — run ./secrets/manage.py generate"
            )
    else:
        errors.append(f"{GENERATED_COMPOSE.name} is missing — run ./secrets/manage.py generate")

    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", ".env", ".env.local"],
        cwd=ROOT, capture_output=True, text=True,
    )
    for path_name in tracked.stdout.split():
        errors.append(f"{path_name} is tracked by git — plaintext secrets must not be committed")

    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    if errors:
        return 1
    for warning in warnings:
        print(f"warn: {warning}")
    print(f"secrets check passed ({len(registry)} registered, {len(vault_keys)} in vaults)")
    return 0


def read_staged(path: Path) -> str:
    relative = path.relative_to(ROOT)
    proc = subprocess.run(
        ["git", "show", f":{relative}"], cwd=ROOT, capture_output=True, text=True
    )
    return proc.stdout if proc.returncode == 0 else path.read_text()


def sops_native_key_path() -> Path:
    if sys.platform == "darwin":
        base = Path.home() / "Library" / "Application Support"
    elif sys.platform == "win32":
        base = Path(os.environ.get("AppData", Path.home() / "AppData" / "Roaming"))
    else:
        base = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return base / "sops" / "age" / "keys.txt"


def link_native_key_path() -> Path | None:
    """Symlink sops' native lookup at the pinned key so a bare `sops -d` works.

    Never replaces a real file — that could be an identity for another vault.
    """
    native = sops_native_key_path()
    if native == AGE_KEY_FILE or not AGE_KEY_FILE.exists() or native.exists():
        return None
    native.parent.mkdir(parents=True, exist_ok=True)
    native.symlink_to(AGE_KEY_FILE)
    return native


def age_identity_public_key() -> str | None:
    """This host's age public key, or None if it has no identity yet."""
    if not AGE_KEY_FILE.exists():
        return None
    return next(
        (
            line.split(":", 1)[1].strip()
            for line in AGE_KEY_FILE.read_text().splitlines()
            if line.startswith(AGE_PUBLIC_KEY_COMMENT)
        ),
        None,
    )


def ensure_age_identity() -> str:
    """Create or adopt this host's identity, and return its public key."""
    require_tools("age-keygen")
    stranded = misplaced_age_key()
    if stranded:
        # Adopt rather than generate: a second identity would orphan the first,
        # which is probably already a vault recipient.
        AGE_KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(stranded), str(AGE_KEY_FILE))
        os.chmod(AGE_KEY_FILE, AGE_KEY_FILE_MODE)
        print(f"adopted age identity {stranded} -> {AGE_KEY_FILE}")
    elif AGE_KEY_FILE.exists():
        print(f"age identity already present at {AGE_KEY_FILE}")
    else:
        AGE_KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
        proc = subprocess.run(
            ["age-keygen", "-o", str(AGE_KEY_FILE)], capture_output=True, text=True
        )
        if proc.returncode != 0:
            raise SecretsError(f"age-keygen failed:\n{proc.stderr.strip()}")
        os.chmod(AGE_KEY_FILE, AGE_KEY_FILE_MODE)
        print(f"created age identity at {AGE_KEY_FILE}")

    public_key = age_identity_public_key()
    if public_key is None:
        raise SecretsError(f"no public key found in {AGE_KEY_FILE}")
    return public_key


def suggested_holder_label() -> str:
    """A default holder name for this machine, in .sops.yaml's user@host shape."""
    import getpass
    import socket

    return f"{getpass.getuser()}@{socket.gethostname().split('.')[0]}"


def vault_recipients(path: Path) -> list[str]:
    """The age keys a vault is currently wrapped for, from its own metadata.

    Read from the ciphertext rather than from .sops.yaml, so this answers "who
    can open this file" instead of "who was supposed to be able to".
    """
    return [
        line.split("=", 1)[1]
        for line in path.read_text().splitlines()
        if line.startswith(f"{SOPS_METADATA_PREFIX}age") and "recipient" in line
    ]


def existing_vaults() -> list[Path]:
    return [
        vault_path(env_name)
        for env_name in (COMMON_ENV, *ENVIRONMENTS)
        if vault_path(env_name).exists()
    ]


def rotate_vaults() -> list[Path]:
    """Re-wrap every vault's data key for the current recipient list."""
    rotated = []
    for path in existing_vaults():
        run_sops(["updatekeys", "--yes", path.name], capture=False)
        rotated.append(path)
    return rotated


def add_recipient(text: str, key: str, label: str) -> str | None:
    """Insert a recipient into .sops.yaml, keeping the comment-above-key shape.

    Returns None when the key is already listed, so callers can tell "nothing
    to do" from "edited" — a re-run of a half-finished enrollment should still
    re-wrap the vaults rather than adding the key twice.
    """
    lines = text.splitlines(keepends=True)
    recipient_lines = [i for i, line in enumerate(lines) if RECIPIENT_RE.match(line)]
    if any(RECIPIENT_RE.match(lines[i]).group(2) == key for i in recipient_lines):
        return None

    if recipient_lines:
        last = recipient_lines[-1]
        insert_at, indent = last + 1, RECIPIENT_RE.match(lines[last]).group(1)
    else:
        block = next((i for i, line in enumerate(lines) if AGE_BLOCK_RE.match(line)), None)
        if block is None:
            raise SecretsError(
                f"secrets/{SOPS_CONFIG.name} has no `- age:` block to add a recipient to"
            )
        insert_at = block + 1
        indent = AGE_BLOCK_RE.match(lines[block]).group(1) + AGE_BLOCK_ITEM_INDENT

    if not lines[insert_at - 1].endswith("\n"):
        lines[insert_at - 1] += "\n"
    lines[insert_at:insert_at] = [f"{indent}# {label}\n", f"{indent}- {key}\n"]
    return "".join(lines)


def require_decrypt_access() -> None:
    """Fail before touching anything if this host cannot open the vaults.

    `updatekeys` decrypts before it re-encrypts, so a non-recipient running
    enroll would get a key-lookup failure with .sops.yaml already edited.
    """
    common = vault_path(COMMON_ENV)
    if not common.exists():
        raise SecretsError(
            f"secrets/{common.name} does not exist — there is no vault to enroll into.\n"
            "First-time setup: ./secrets/manage.py enroll, then ./secrets/manage.py import"
        )
    public_key = age_identity_public_key()
    if public_key is None:
        raise SecretsError(
            f"this host has no age identity at {AGE_KEY_FILE}.\n"
            "Enrolling someone else has to be done from a host that is already a recipient."
        )
    if public_key not in vault_recipients(common):
        raise SecretsError(
            f"this host is not a recipient of secrets/{common.name}, so it cannot re-wrap it.\n"
            "Run this from a machine that can already decrypt."
        )


def cmd_enroll(args: argparse.Namespace) -> int:
    """Both halves of the enrollment handshake, told apart by the key argument.

    On the machine being enrolled, bare `enroll` mints the identity and prints
    the exact command for the other side to run. On a machine that can already
    decrypt, `enroll <key>` adds the recipient, re-wraps every vault, and
    checks the key actually landed — the hand-edit and the easily-forgotten
    `rotate` that used to be steps 2 and 3.
    """
    if args.key is None:
        return enroll_this_host()
    return enroll_recipient(args.key, args.as_name, args.note)


def enroll_this_host() -> int:
    public_key = ensure_age_identity()
    if link_native_key_path():
        print("linked sops' default lookup at the same key (so `sops -d` works by hand)")
    print()
    print("Public key for this host:")
    print(f"  {public_key}")
    print()
    if vault_path(COMMON_ENV).exists():
        print("On a machine that can already decrypt, run:")
        print(f'  ./secrets/manage.py enroll {public_key} --as "{suggested_holder_label()}"')
    else:
        print("No vault exists yet. Seed one with:")
        print("  ./secrets/manage.py import --source .env")
    print()
    print(PRIVATE_KEY_WARNING)
    return 0


def enroll_recipient(key: str, name: str | None, note: str) -> int:
    if not AGE_PUBLIC_KEY_RE.fullmatch(key):
        raise SecretsError(
            f"'{key}' is not an age public key.\n"
            "Expected the age1… line printed by `./secrets/manage.py enroll` "
            "on the machine being enrolled."
        )
    if not name:
        raise SecretsError(
            "--as is required: an unlabelled key is one nobody can identify to remove later.\n"
            f'    ./secrets/manage.py enroll {key} --as "wc@laptop" --note "primary dev machine"'
        )
    require_decrypt_access()

    label = f"{name} — {note}" if note else name
    updated = add_recipient(SOPS_CONFIG.read_text(), key, label)
    if updated is None:
        print(f"already a recipient in {SOPS_CONFIG.name} — re-wrapping anyway")
    else:
        SOPS_CONFIG.write_text(updated)
        print(f"added {label} to secrets/{SOPS_CONFIG.name}")

    rotated = rotate_vaults()
    for path in rotated:
        print(f"rotated secrets/{path.name}")

    # The .sops.yaml edit and the re-wrap are separate facts. Read the second
    # one back off the ciphertext so a silent no-op cannot pass for success.
    unwrapped = [path.name for path in rotated if key not in vault_recipients(path)]
    if unwrapped:
        raise SecretsError(
            f"the new key is not a recipient of: {', '.join(unwrapped)}\n"
            "The .sops.yaml edit landed but the re-wrap did not take. Re-run this command."
        )

    print()
    print(f"{label} can now decrypt {len(rotated)} vault(s). Commit both halves together —")
    print("a .sops.yaml naming a recipient the ciphertext lacks is worse than neither:")
    print(f"  git add secrets/{SOPS_CONFIG.name} secrets/*.enc.env")
    print(f'  git commit -m "secrets: enroll {name}"')
    return 0


def cmd_init(_args: argparse.Namespace) -> int:
    """Kept because runbooks and error hints say `init`; `enroll` is the same thing."""
    return enroll_this_host()


def cmd_rotate(_args: argparse.Namespace) -> int:
    for path in rotate_vaults():
        print(f"rotated secrets/{path.name}")
    print()
    print("This re-wraps the data key. A removed holder still knows the current")
    print("values — rotate the credentials at their providers too.")
    return 0


def cmd_recipients(_args: argparse.Namespace) -> int:
    for path in existing_vaults():
        recipients = vault_recipients(path)
        print(f"secrets/{path.name}: {len(recipients)} recipient(s)")
        for recipient in recipients:
            print(f"  {recipient}")
    return 0


COMMANDS = {
    "ls": (cmd_ls, "list secrets and where each has a value"),
    "get": (cmd_get, "print one value"),
    "set": (cmd_set, "set one value"),
    "add": (cmd_add, "register a new secret and set its value"),
    "rm": (cmd_rm, "remove a secret from the registry and all vaults"),
    "edit": (cmd_edit, "open a vault in $EDITOR"),
    "exec": (cmd_exec, "run a command with secrets in its environment"),
    "export": (cmd_export, "print KEY=VALUE lines (Tiltfile only)"),
    "generate": (cmd_generate, "regenerate docker-compose.secrets.yml"),
    "check": (cmd_check, "validate registry, vaults and generated output"),
    "enroll": (cmd_enroll, "mint this host's key, or add another host's as a recipient"),
    "init": (cmd_init, "alias for `enroll` with no key"),
    "rotate": (cmd_rotate, "re-encrypt for the current recipients"),
    "recipients": (cmd_recipients, "list age keys that can decrypt"),
    "import": (cmd_import, "one-time: seed vaults from a plaintext dotenv"),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    subs = parser.add_subparsers(dest="command", required=True)
    for name, (handler, help_text) in COMMANDS.items():
        sub = subs.add_parser(name, help=help_text)
        sub.set_defaults(handler=handler)
        if name in {"exec", "export", "get"}:
            sub.add_argument("environment", choices=ENVIRONMENTS)
        if name in {"edit"}:
            sub.add_argument("environment", choices=(COMMON_ENV, *ENVIRONMENTS))
        if name == "exec":
            sub.add_argument("command", nargs=argparse.REMAINDER)
        if name in {"get", "set", "add", "rm"}:
            sub.add_argument("name")
        if name in {"set", "add"}:
            sub.add_argument(
                "environment", nargs="?", default=COMMON_ENV,
                choices=(COMMON_ENV, *ENVIRONMENTS),
            )
            sub.add_argument("--value", help="value (omit to be prompted without echo)")
        if name == "add":
            sub.add_argument("--description", required=True)
            sub.add_argument("--consumers", required=True, type=lambda s: s.split(","))
            sub.add_argument("--required-in", default="", dest="required_in",
                             type=lambda s: [p for p in s.split(",") if p])
        if name == "generate":
            sub.add_argument("--check", action="store_true",
                             help="fail if the generated file is stale")
        if name == "check":
            sub.add_argument("--staged", action="store_true")
        if name == "import":
            sub.add_argument("--source", default=str(ROOT / ".env"))
            sub.add_argument("--force", action="store_true")
        if name == "enroll":
            sub.add_argument(
                "key", nargs="?",
                help="age public key to add as a recipient; omit to mint and print this host's",
            )
            sub.add_argument("--as", dest="as_name", metavar="NAME",
                             help="who holds the key, e.g. wc@laptop")
            sub.add_argument("--note", default="",
                             help="what the machine is, e.g. 'deploy host'")

    args = parser.parse_args(argv)
    try:
        return args.handler(args)
    except SecretsError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
